CC=gcc #openmpicc
CFLAGS=-c -O3 -std=gnu99
LDFLAGS=-lfftw3_threads -lfftw3 -lhdf5 -lm
SOURCES=main_2d.c model_2d.c time_schemes.c operators.c fft_routines_2d.c hdf5_routines_2d.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=euler_2d
LIBPATTERNS = lib%.a
INC = -I/usr/include/
LIB = -L/usr/lib/

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS)
	$(CC)  $(OBJECTS) -o $@ $(LDFLAGS) $(LIB)

.c.o: $(LDFLAGS)
	$(CC) $(CFLAGS) $< -o $@ $(INC) 

clean:
	rm *.o
